server:
  port: 8082
dubbo:
  application:
    name: hello
  registry:
    address: 224.5.6.7:1234
    protocol: multicast
  scan:
    base-packages: com.calpis.interview.dubbo.service
  protocol:
    name: dubbo
    port: 20882
  config-center:
    timeout: 60000