server:
  port: ${random.int[10000,19999]}
dubbo:
  application:
    name: hello-provider
  registry:
    address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    protocol: zookeeper
  protocol:
    name: dubbo
    port: ${random.int[20880,30880]}